# more on http://wiki.ros.org/move_base

controller_frequency: 0.1
recovery_behavior_enabled: true
clearing_rotation_allowed: false

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.2 # A tolerance on the goal point for the planner.

TebLocalPlannerROS:
  allow_init_with_backwards_motion: true

  # Robot
  max_vel_x: 0.25
  max_vel_y: 0.0
  max_vel_x_backwards: 0.25
  max_vel_y_backwards: 0.25
  max_vel_theta: 0.1
  acc_lim_x: 0.05
  acc_lim_y: 0.0
  acc_lim_theta: 0.025
  wheelbase: 0.44
  min_turning_radius: 0.5
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "point" # DO NOT CHANGE THIS (at least not to polygon), or it will give weird planning behavior
    radius: 0.75 # for type "circular"
    line_start: [-0.3, 0.0] # for type "line"
    line_end: [0.3, 0.0] # for type "line"
    front_offset: 0.2 # for type "two_circles"
    front_radius: 0.2 # for type "two_circles"
    rear_offset: 0.2 # for type "two_circles"
    rear_radius: 0.2 # for type "two_circles"
    vertices: [ [0.4, 0.4], [0.4, -0.4], [-0.4, -0.4], [-0.4, 0.4] ] # for type "polygon"

  # Obstacles
  min_obstacle_dist: 0.45
  penalty_epsilon: 0.01

  #weight_kinematics_turning_radius: 0.0
